
package rs.crhov.tijanap.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPlService", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IPlService {


    /**
     * 
     * @param privredniSubjektiUlazniPodaci
     * @return
     *     returns rs.crhov.tijanap.soap.ArrayOfPrivredniSubjekat
     */
    @WebMethod(operationName = "PreuzmiPodatkeOPrivrednomSubjektu", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/PreuzmiPodatkeOPrivrednomSubjektu")
    @WebResult(name = "PrivredniSubjektiPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "PreuzmiPodatkeOPrivrednomSubjektu", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.PreuzmiPodatkeOPrivrednomSubjektu")
    @ResponseWrapper(localName = "PreuzmiPodatkeOPrivrednomSubjektuResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.PreuzmiPodatkeOPrivrednomSubjektuResponse")
    public ArrayOfPrivredniSubjekat preuzmiPodatkeOPrivrednomSubjektu(
        @WebParam(name = "privredniSubjektiUlazniPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
        PrivredniSubjektiUlazniPodaci privredniSubjektiUlazniPodaci);

    /**
     * 
     * @param privredniSubjektiPromenePoDatumuUlazniPodaci
     * @return
     *     returns rs.crhov.tijanap.soap.ArrayOfPrivredniSubjekat
     */
    @WebMethod(operationName = "PreuzmiPromenePodatakaOPrivrednimSubjektima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/PreuzmiPromenePodatakaOPrivrednimSubjektima")
    @WebResult(name = "privredniSubjektiPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "PreuzmiPromenePodatakaOPrivrednimSubjektima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.PreuzmiPromenePodatakaOPrivrednimSubjektima")
    @ResponseWrapper(localName = "PreuzmiPromenePodatakaOPrivrednimSubjektimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.PreuzmiPromenePodatakaOPrivrednimSubjektimaResponse")
    public ArrayOfPrivredniSubjekat preuzmiPromenePodatakaOPrivrednimSubjektima(
        @WebParam(name = "privredniSubjektiPromenePoDatumuUlazniPodaci", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
        PrivredniSubjektiPromenePoDatumu privredniSubjektiPromenePoDatumuUlazniPodaci);

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciODelatnostima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciODelatnostima")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciODelatnostima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciODelatnostima")
    @ResponseWrapper(localName = "SviPodaciODelatnostimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciODelatnostimaResponse")
    public Sifarnik sviPodaciODelatnostima();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciODrzavama", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciODrzavama")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciODrzavama", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciODrzavama")
    @ResponseWrapper(localName = "SviPodaciODrzavamaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciODrzavamaResponse")
    public Sifarnik sviPodaciODrzavama();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOFunkcijamaOsnivacaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOFunkcijamaZakonskogZastupnikaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOGrupamaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOGrupamaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOGrupamaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOGrupamaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOGrupamaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOGrupamaDelatnostiResponse")
    public Sifarnik sviPodaciOGrupamaDelatnosti();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOMestima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOMestima")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOMestima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOMestima")
    @ResponseWrapper(localName = "SviPodaciOMestimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOMestimaResponse")
    public Sifarnik sviPodaciOMestima();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblastimaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblastimaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblastimaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblastimaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOOblastimaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblastimaDelatnostiResponse")
    public Sifarnik sviPodaciOOblastimaDelatnosti();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOOblicimaOrganizovanjaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOdsecimaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOdsecimaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOdsecimaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOdsecimaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOOdsecimaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOdsecimaDelatnostiResponse")
    public Sifarnik sviPodaciOOdsecimaDelatnosti();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOkruzima", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOkruzima")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOkruzima", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOkruzima")
    @ResponseWrapper(localName = "SviPodaciOOkruzimaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOkruzimaResponse")
    public Sifarnik sviPodaciOOkruzima();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOpstinama", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOpstinama")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOpstinama", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOpstinama")
    @ResponseWrapper(localName = "SviPodaciOOpstinamaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOpstinamaResponse")
    public Sifarnik sviPodaciOOpstinama();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOPravnimFormama", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOPravnimFormama")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOPravnimFormama", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOPravnimFormama")
    @ResponseWrapper(localName = "SviPodaciOPravnimFormamaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOPravnimFormamaResponse")
    public Sifarnik sviPodaciOPravnimFormama();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOSektorimaDelatnosti", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOSektorimaDelatnosti")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOSektorimaDelatnosti", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOSektorimaDelatnosti")
    @ResponseWrapper(localName = "SviPodaciOSektorimaDelatnostiResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOSektorimaDelatnostiResponse")
    public Sifarnik sviPodaciOSektorimaDelatnosti();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaPreduzetnika", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaPreduzetnika")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaPreduzetnika", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaPreduzetnika")
    @ResponseWrapper(localName = "SviPodaciOStatusimaPreduzetnikaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaPreduzetnikaResponse")
    public Sifarnik sviPodaciOStatusimaPreduzetnika();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOStatusimaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOStatusimaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOStatusimaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaUdruzenjaResponse")
    public Sifarnik sviPodaciOStatusimaUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOStatusimaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOStatusimaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenjaResponse")
    public Sifarnik sviPodaciOTipoviimaOblastiOstvarivanjaCiljevaUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipoviimaZabeleskiUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipoviimaZabeleskiUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipoviimaZabeleskiUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipoviimaZabeleskiUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOTipoviimaZabeleskiUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipoviimaZabeleskiUdruzenjaResponse")
    public Sifarnik sviPodaciOTipoviimaZabeleskiUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaCiljevaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaCiljevaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaCiljevaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaCiljevaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaCiljevaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaCiljevaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaCiljevaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaClanaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaClanaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaClanaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaClanaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOTipovimaClanaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaClanaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOTipovimaClanaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaFunkcijeZastupnikaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaJezika", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaJezika")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaJezika", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaJezika")
    @ResponseWrapper(localName = "SviPodaciOTipovimaJezikaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaJezikaResponse")
    public Sifarnik sviPodaciOTipovimaJezika();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaKapitalaPrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaKapitalaPrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaKapitalaPrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaKapitalaPrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOTipovimaKapitalaPrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaKapitalaPrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOTipovimaKapitalaPrivrednogDrustva();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaKapitalaZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaKapitalaZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaKapitalaZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaKapitalaZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaKapitalaZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaKapitalaZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaKapitalaZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaLica", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaLica")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaLica", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaLica")
    @ResponseWrapper(localName = "SviPodaciOTipovimaLicaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaLicaResponse")
    public Sifarnik sviPodaciOTipovimaLica();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaNacinaPromene", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaNacinaPromene")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaNacinaPromene", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaNacinaPromene")
    @ResponseWrapper(localName = "SviPodaciOTipovimaNacinaPromeneResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaNacinaPromeneResponse")
    public Sifarnik sviPodaciOTipovimaNacinaPromene();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaNazivaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaNazivaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaNazivaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaNazivaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOTipovimaNazivaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaNazivaUdruzenjaResponse")
    public Sifarnik sviPodaciOTipovimaNazivaUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaPoslovnogSubjekta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaPoslovnogSubjekta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaPoslovnogSubjekta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaPoslovnogSubjekta")
    @ResponseWrapper(localName = "SviPodaciOTipovimaPoslovnogSubjektaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaPoslovnogSubjektaResponse")
    public Sifarnik sviPodaciOTipovimaPoslovnogSubjekta();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaRegistracionogPostupka", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaRegistracionogPostupka")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaRegistracionogPostupka", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaRegistracionogPostupka")
    @ResponseWrapper(localName = "SviPodaciOTipovimaRegistracionogPostupkaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaRegistracionogPostupkaResponse")
    public Sifarnik sviPodaciOTipovimaRegistracionogPostupka();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaZabeleskiZaduzbineIliFondacije")
    @ResponseWrapper(localName = "SviPodaciOTipovimaZabeleskiZaduzbineIliFondacijeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaZabeleskiZaduzbineIliFondacijeResponse")
    public Sifarnik sviPodaciOTipovimaZabeleskiZaduzbineIliFondacije();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVelicinamaPoslovnogSubjekta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVelicinamaPoslovnogSubjekta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVelicinamaPoslovnogSubjekta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVelicinamaPoslovnogSubjekta")
    @ResponseWrapper(localName = "SviPodaciOVelicinamaPoslovnogSubjektaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVelicinamaPoslovnogSubjektaResponse")
    public Sifarnik sviPodaciOVelicinamaPoslovnogSubjekta();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaZabelezbePreduzetnika", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaZabelezbePreduzetnika")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaZabelezbePreduzetnika", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaZabelezbePreduzetnika")
    @ResponseWrapper(localName = "SviPodaciOVrstamaZabelezbePreduzetnikaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaZabelezbePreduzetnikaResponse")
    public Sifarnik sviPodaciOVrstamaZabelezbePreduzetnika();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaZabelezbePrivrednogDrustva", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaZabelezbePrivrednogDrustva")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaZabelezbePrivrednogDrustva", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaZabelezbePrivrednogDrustva")
    @ResponseWrapper(localName = "SviPodaciOVrstamaZabelezbePrivrednogDrustvaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaZabelezbePrivrednogDrustvaResponse")
    public Sifarnik sviPodaciOVrstamaZabelezbePrivrednogDrustva();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaZabelezbeSportskogUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaZabelezbeSportskogUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaZabelezbeSportskogUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaZabelezbeSportskogUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOVrstamaZabelezbeSportskogUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaZabelezbeSportskogUdruzenjaResponse")
    public Sifarnik sviPodaciOVrstamaZabelezbeSportskogUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenjaResponse")
    public Sifarnik sviPodaciOVrstamaOblikaOrganizovanjaSportskogUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstamaGraneSporta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstamaGraneSporta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstamaGraneSporta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaGraneSporta")
    @ResponseWrapper(localName = "SviPodaciOVrstamaGraneSportaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstamaGraneSportaResponse")
    public Sifarnik sviPodaciOVrstamaGraneSporta();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblicimaOrganizovanjaUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblicimaOrganizovanjaUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblicimaOrganizovanjaUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblicimaOrganizovanjaUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOOblicimaOrganizovanjaUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblicimaOrganizovanjaUdruzenjaResponse")
    public Sifarnik sviPodaciOOblicimaOrganizovanjaUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaKomore", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaKomore")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaKomore", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaKomore")
    @ResponseWrapper(localName = "SviPodaciOStatusimaKomoreResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaKomoreResponse")
    public Sifarnik sviPodaciOStatusimaKomore();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaNazivaKomore", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaNazivaKomore")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaNazivaKomore", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaNazivaKomore")
    @ResponseWrapper(localName = "SviPodaciOTipovimaNazivaKomoreResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaNazivaKomoreResponse")
    public Sifarnik sviPodaciOTipovimaNazivaKomore();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaStecajneMase", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaStecajneMase")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaStecajneMase", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaStecajneMase")
    @ResponseWrapper(localName = "SviPodaciOStatusimaStecajneMaseResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaStecajneMaseResponse")
    public Sifarnik sviPodaciOStatusimaStecajneMase();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOTipovimaOsnivaca", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOTipovimaOsnivaca")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOTipovimaOsnivaca", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaOsnivaca")
    @ResponseWrapper(localName = "SviPodaciOTipovimaOsnivacaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOTipovimaOsnivacaResponse")
    public Sifarnik sviPodaciOTipovimaOsnivaca();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOStatusimaSportskogUdruzenja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOStatusimaSportskogUdruzenja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOStatusimaSportskogUdruzenja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaSportskogUdruzenja")
    @ResponseWrapper(localName = "SviPodaciOStatusimaSportskogUdruzenjaResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOStatusimaSportskogUdruzenjaResponse")
    public Sifarnik sviPodaciOStatusimaSportskogUdruzenja();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciONacinuNastankaStecajneMase", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciONacinuNastankaStecajneMase")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciONacinuNastankaStecajneMase", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciONacinuNastankaStecajneMase")
    @ResponseWrapper(localName = "SviPodaciONacinuNastankaStecajneMaseResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciONacinuNastankaStecajneMaseResponse")
    public Sifarnik sviPodaciONacinuNastankaStecajneMase();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOVrstiZadruge", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOVrstiZadruge")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOVrstiZadruge", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstiZadruge")
    @ResponseWrapper(localName = "SviPodaciOVrstiZadrugeResponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOVrstiZadrugeResponse")
    public Sifarnik sviPodaciOVrstiZadruge();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciODiscipliniSporta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciODiscipliniSporta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciODiscipliniSporta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciODiscipliniSporta")
    @ResponseWrapper(localName = "SviPodaciODiscipliniSportaReponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciODiscipliniSportaReponse")
    public Sifarnik sviPodaciODiscipliniSporta();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciOOblastiSporta", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciOOblastiSporta")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciOOblastiSporta", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblastiSporta")
    @ResponseWrapper(localName = "SviPodaciOOblastiSportaReponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciOOblastiSportaReponse")
    public Sifarnik sviPodaciOOblastiSporta();

    /**
     * 
     * @return
     *     returns rs.crhov.tijanap.soap.Sifarnik
     */
    @WebMethod(operationName = "SviPodaciORazloguBrisanja", action = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/IPlService/SviPodaciORazloguBrisanja")
    @WebResult(name = "sifarnik", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/")
    @RequestWrapper(localName = "SviPodaciORazloguBrisanja", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciORazloguBrisanja")
    @ResponseWrapper(localName = "SviPodaciORazloguBrisanjaReponse", targetNamespace = "http://BusinessEntityDataMediationModule/serviceExport/BusinessEntityDataInterface/", className = "rs.crhov.tijanap.soap.SviPodaciORazloguBrisanjaReponse")
    public Sifarnik sviPodaciORazloguBrisanja();

}
